name: SmallRye Pre-Release

on:
  pull_request:
    paths:
    - '.github/project.yml'

jobs:
  release:
    name: Pre-release checks
    runs-on: ubuntu-latest

    steps:
      - name: Retrieve project metadata
        id: metadata
        uses: radcortez/project-metadata-action@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'

      - name: Validate version
        if: contains(steps.metadata.outputs.current-version, 'SNAPSHOT')
        run: |
          echo '::error::Cannot release a SNAPSHOT version.'
          exit 1

      - name: Milestone review
        uses: radcortez/milestone-review-action@main
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          milestone-title: ${{steps.metadata.outputs.current-version}}
